### ISSUE TITLE
Web console logger

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/MSOPortal#103]
Basic web interface to show logs.
Based on django.
Take advantage of socket.io for asynchronous/real-time log visualization

**Comment by victorsndvg** [comment]
Integration into the portal pending

**Comment by victorsndvg** [comment]
HI @emepetres , How this task goes? is it testable from the Portal?

**Comment by emepetres** [comment]
Hi @victorsndvg , I sent you an email last monday about that.

Basically I'm waiting for you to put the server at http://logging.mso4sc.eu:8080, and also the blueprint example.

**Comment by victorsndvg** [comment]
Sorry, I didn't understand correctly your email. I'm going to send the example this morning

**Comment by victorsndvg** [comment]
Thanks @emepetres ,
we can close this now :)
