### ISSUE TITLE
BUG in MSO4SC portal: cannot login from a network with limited port access

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#109]
students have network access through a limited wifi network. Only 22 and 80 8080 are open.
As a consequence, they cannot login to the platform and need to use a different network to access it.
there is no message to the end-user about this issue on the home page of the platform.

**Comment by emepetres** [comment]
I imagin I could change the marketplace and datacatalogue to por 80, and IDM to port 8080. However we are planning to move everything to HTTPs (port 443), I imagine this port is already open in your network right?

**Comment by emepetres** [comment]
Depends on #68 and #69

**Comment by emepetres** [comment]
I took advantage of work in #69 to move marketplace and datacatalogue to port 80. Everything is now at ports 80, or 443 except marketplace apis which are at 8080.
