### ISSUE TITLE
Marketplace Bug : impossible to checkout a new product

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#114]
It is currently impossible to checkout a new product. In the checkout window we get this message in the screenshot below and the checkout button is not clickable

<img width="716" alt="screenshot 2018-06-12 04 37 37" src="https://user-images.githubusercontent.com/151693/41270009-090256c4-6e09-11e8-93a6-90d37dcce111.png">

**Comment by emepetres** [comment]
It is a marketplace bug! I'm trying to reach the developer to get fixed ASAP, let's wait to see what he says.

As a workaround, new products + offerings works, what doesn't work is operation with objects created before today. I imagine it is not acceptable but I just wanted to write down in case it is a temporary solution for someone.

**Comment by prudhomm** [comment]
So the solution is to create new products?

**Comment by emepetres** [comment]
Ok so the problem is the change from port 8004 to port 80, that the marketplace is not prepared for that.

Two feasible solutions:
1.- Stay on port 80, remove all information in the marketplace and start again.
2.- Go back to port 8004

**Comment by Trophime** [comment]
Option 1 requires a lot of "work"
Option 2 requires some settings from IT guys and/or the use of VPN to closed port issue...

**Comment by emepetres** [comment]
We resolved it deleting all marketplace data.
