### ISSUE TITLE
Login from an incognito windows web brower broken with Https

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#116]
Try to login using a incognito windows web brower broken, breaks you to IDM
After entering credentials you are transferred to *IDM*

No way to login!
Same behaviour with Chromium and Firefox

**Comment by Trophime** [comment]
It's only true for https

**Comment by romainhild** [comment]
I had the same issue from a normal window.

**Comment by emepetres** [comment]
Is this still valid? I can log in from an incognito window...

**Comment by Trophime** [comment]
unfortunatly yes

**Comment by Trophime** [comment]
seems to be working
