### ISSUE TITLE
feature wanted: select multiple "product order" to validate then at once

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#119]
Would it be possible to select product order to validate then at once instead of doing it one by one?
Would be great for MOOC or courses where there may be a lot of demands...

**Comment by victorsndvg** [comment]
This  is not exactly a solution for this particular problem, but can be an alternative to avoid to manually accept purchases .

It seems that, at least, ``free`` (no price plan) ``digita`` products are automatically accepted when the end-user ``checkout`` the product from the cart.

I need to investigate this alternative a little bit more before ensuring that it works properly. 

This is only a  comment to remember to do some tests. Please, don't play with this alternative, at least until ECMI finishes or we can confirm this is valid.

**Comment by emepetres** [comment]
This is a marketplace feature request and therefore it should be posted in its repository, external to MSO4SC.
