### ISSUE TITLE
Green light after execution not always shown

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/MSOPortal#12]
Hi,

as @VedatDurmaz  comments, portal should always show a green light after a successful execution.

> ... there's just one thing to mention: when all executions are done, the portal prints ... COMPLETED ..., but neither does the blue light switch to green nor does the cloudify status change from started to terminated. though presumably not critical, i don't know how to handle this.

I think you mentioned something about connection closing (Portal -> HPC) after a time limit.

**Comment by emepetres** [comment]
I just realised this was due to cloudify-hpc-plugin#39 . Closing.
