### ISSUE TITLE
UX Bug in Visualisation Page multiple entries for the same tool

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#121]
When creating the desktop, it appears several times, it is a UX Bug
<img width="740" alt="screenshot 2018-06-15 11 57 56" src="https://user-images.githubusercontent.com/151693/41462650-d4ceb59a-7093-11e8-9c77-b99d8ed9dede.png">

**Comment by prudhomm** [comment]
CC: @victorsndvg  what do you think?

**Comment by victorsndvg** [comment]
This doesn't happen to me.

It creates 1 remote desktop per click on `create` button, each one points to a different desktop. 

Desktops timeout at FT2 is 8 hours, if you want to remove each one of them you have to click on `menu > logout` in the topbar of the desktop
