### ISSUE TITLE
Automatically login into AskBot

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#122]
Instead of clicking Q&A, then sign-in, then Fiware button, there should exist a url that, when clicking Q&A, the user is redirected to this url that logs the user in automatically (through the IDM of course).

To be clear, the behaviour clicking Q&A should be the same as now clicking the Fiware button in AskBot

**Comment by victorsndvg** [comment]
:+1:

Perfectly understandable. Till the moment I deactivate other login choices and only fiware is enabled.

I've to take a look to know how to build the request to login directly. TODO
