### ISSUE TITLE
Integrate globus oauth with IDM

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#131]
An MSO4SC user must access the transfer portal using its IDM credentials.

**Comment by emepetres** [comment]
Hi, any news on this?

**Comment by pdiaz123** [comment]
After analyzing the possibility of integrating Keyrock with Globus, it is concluded that it is not possible although Globus Auth supports Oauth2. The main problem is that a Globus Plus subscription is needed which implies costs.
