### ISSUE TITLE
Run instance: Timestamps are wrong

### ISSUE THREAD

**Issue by VikingScientist** [MSO4SC/MSOPortal#139]
<img width="692" alt="screenshot 2018-08-29 09 23 22" src="https://user-images.githubusercontent.com/3500376/44772528-67248900-ab6e-11e8-98c6-f05ae06a38d9.png">

When I create and run an application it somehow manages to create timestamps in the past. The top shows that the job is submitted 2018-08-29, but the timestamps are dated 2018-07-04.

What is going on here?

**Comment by emepetres** [comment]
www subdomain was added by @budait

**Comment by emepetres** [comment]
Duplicated of #28
