### ISSUE TITLE
Feature request: "add another" button when editing datasets

### ISSUE THREAD

**Issue by VikingScientist** [MSO4SC/MSOPortal#140]
* Data catalogue
* Datasets
* Add dataset

gives the following screen 

<img width="692" alt="screenshot 2018-08-29 09 41 52" src="https://user-images.githubusercontent.com/3500376/44773192-3ba29e00-ab70-11e8-9a64-1f4002b7883d.png">

Notice in particular the button "save & add another" at the bottom.

If you try and **edit** an existing dataset by

* Data catalogue
* Datasets
* (click existing dataset)
* Manage
* Resources
* Add new resource

we get the following screen which is missing the "save & add another"-button. After clicking "add" you basically have to navigate all the way back to this screen again to keep editing.

<img width="692" alt="screenshot 2018-08-29 09 39 53" src="https://user-images.githubusercontent.com/3500376/44773347-a94eca00-ab70-11e8-8b87-9f1375f2cbac.png">

**Comment by emepetres** [comment]
The data catalogue is based on CKAN, and its development is external to MSO4SC. I suggest posting this issue as a feature request in the CKAN repo: https://github.com/ckan/ckan
