### ISSUE TITLE
new feature: CKAN export add the possibility to export a list of files/directories

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#144]
It will be great to have the opportunity to publish a list of files to CKAN instead of a single file.
Would it be possible to export directory (as zipped tarballs for instance)?

By the way it seems that there is a filesize limit for the upload into CKAN.
Can you tell wich limit?

**Comment by Trophime** [comment]
@emepetres what is the actual status of this request?
I don't understand if it won't be implemented or simply closed?

**Comment by emepetres** [comment]
@Trophime this is a request that had to be implemented in CKAN itself, so I understand is beyond the MSO4SC scope. That's way it is marked as "invalid".

Of course we could add a workaround by making a web page that would take a directory and upload it to ckan using its API. But I think the best way would be to ask CKAN developers to implement this feature.

**Comment by Trophime** [comment]
Thanks it's more clear.
The only way to go is to create an archive within the `-post` command right?
By the way is that command available only in the canary hpc-plugin?

**Comment by emepetres** [comment]
`post` its only available on canary, but it works only with SingularityJob type. Nevertheless the `publish` keyword receive a list of files to be published (see README.adoc), so you can specify all the files you want to publish there.
