### ISSUE TITLE
Loading licenses from portal

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#149]
It will be great to have in *settings* a section dedicated to license.
This way we could:
* upload license keys very easily in a specific directory in the HPC ressources.
* mount this directory for latter loading the license in the workload manager script

Typical use case for that is the meshing for instance.

PS: this will only work for floating license key, I guess, provided the correct ip(s) for the HPC ressource  are allowed within the key

**Comment by victorsndvg** [comment]
Hi @Trophime ,

what about using the Datacatalogue to privately store your floating license file? 

You can add it into your `organization` or `group` to be only shared with members of your team.

Then you can select the license from the Experiments tool by selecting the proper file stored in the DataCatalogue. Then, during bootstrap you can manage to put it in the right place and, from the blueprint, mount the downloaded license into your container, and in the revert process you can remove the file if you want.

How it sounds for you?

**Comment by victorsndvg** [comment]
Ok, great!

Then I'm going to close the issue. 

Feel free to open it again if needed.
