### ISSUE TITLE
Application instance cannot be destroyed : Eye2brain-Level0

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#152]
It is not possible to remove / destroy Eye2brain-Level0 applications and it is not usable as well

**Comment by emepetres** [comment]
Deleted. @prudhomm you have to manually delete any execution/deployment/blueprint in the orchestrator. If there is any execution in "force-cancelling", you can put it as "cancelled" with the script "force-cancel" in resources folder.

**Comment by Trophime** [comment]
The params to use are the same as the credentials for MSOOrchestrator-cli?

**Comment by Trophime** [comment]
The point is that with this user/password I get:
```
{"message": "User unauthorized: Authentication failed for <User username=`admin`>", "error_code": "unauthorized_error", "server_traceback": ""}
```

**Comment by prudhomm** [comment]
@emepetres it does not work. I tried it of course but it seems that it is in such  state that it does not work to force cancel

**Comment by victorsndvg** [comment]
@Trophime , you only have to write down the password. The user is, as default, the default one.

@prudhomm , can you please paste the error you get? is the right way to identify and fix issues

**Comment by victorsndvg** [comment]
@prudhomm , sorry if I sound rude. To better explain myself, I've created a list of issue templates to help to reduce the number of iterations needed to solve problems.

In this case, can you follow this template to explain exactly what you need?
https://github.com/MSO4SC/MSOPortal/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by victorsndvg** [comment]
@prudhomm

**Comment by victorsndvg** [comment]
(to myself: remember, 1st comment, then reopen)

I'have manually uploaded a blueprint with the right name (but is not the right blueprint). Please, try to remove the application and then to reupload it again with the right blueprint.

Is the `eye2brain-level0` (lowercase) issue still there? 
I cannot see any deployment or execution with this name

**Comment by prudhomm** [comment]
@victorsndvg I could remove the app now. I remember that the app was created by mistake without a blueprint and it was accepted. then you cannot remove or at least I don't know how.
now it is goo and the issue can be closed
