### ISSUE TITLE
Inaccessible applications and unable to start instances

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#153]
I have a few applications available such as eye2brain but I cannot access them with my Cemosis account

I attached a screenshot
<img width="844" alt="screenshot 2018-11-09 08 38 35" src="https://user-images.githubusercontent.com/151693/48249419-607e8180-e3fb-11e8-9825-6cbcec1bdca3.png">

**Comment by victorsndvg** [comment]
@prudhomm ,

this is an already known bug. You have to enter and login, at least once, in the Marketplace.

The the message will disappear.

**Comment by prudhomm** [comment]
@victorsndvg could you put the reference to the corresponding issue ?

**Comment by victorsndvg** [comment]
Original issue: #142
