### ISSUE TITLE
Impossible to stop an application or destroy a running instance

### ISSUE THREAD

**Issue by lsala** [MSO4SC/MSOPortal#157]
**Describe the bug**
I cannot destroy an instance that is currently running or stop an application that is running. 
For some reasons maybe I have put some wrong information and I don't want to waste time to keep on running the wrong simulation and I want to stop it.
It is related also to issue #156 .

**Error message**
Removing error: 400: Can't delete deployment test-tutorial_001 - There are running executions for this deployment. Running executions ids: 013409ab-b328-46b3-accc-66f0c028db82

**To Reproduce**
Run any application and then try to destroy it (`Force destroy instance` or `Destroy instance`)

**Expected behavior**
I expect that if I click on `Force destroy instance` the portal is stopping the applications and destroying my instance even if it's running.

**Comment by emepetres** [comment]
Yep, the 'Stop/Cancel button is still to be implemented ( #8 ) . For now, you can use the orchestrator CLI to cancel a running execution manually. Then you can destroy it from the portal.

**Comment by lsala** [comment]
Is there a documentation on how to use the orchestrator CLI ?

**Comment by emepetres** [comment]
Go to MSOOrchestrator-CLI repo
