### ISSUE TITLE
Add doc for changing offering in market place

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#22]
Hi,
would it be possible to add some docs about the "life cycle" of offering?
What are the best practices to change an "offering" in the markeplace?

**Comment by emepetres** [comment]
At the documentation there is a link to http://business-api-ecosystem.readthedocs.io/en/v5.4.1/user-programmer-guide.html where all the specifics of the marketplace are explained in detail. If you think we should add other kind of information let me know.
