### ISSUE TITLE
Logs: Bad timezone

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#28]
The execution logs seems to shown with a bad timezone.

**Comment by victorsndvg** [comment]
I think host timezone can be mounted inside the container. Take a look to this, here is the solution for linux based systems: https://forums.docker.com/t/synchronize-timezone-from-host-to-container/39116

**Comment by VikingScientist** [comment]
I'll just leave this screenshot here. 

<img width="692" alt="screenshot 2018-08-29 09 23 22" src="https://user-images.githubusercontent.com/3500376/44772528-67248900-ab6e-11e8-98c6-f05ae06a38d9.png">
