### ISSUE TITLE
Basic/Advanced input properties

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#32]
When wants to create a new instance of a concrete application, two tabs will be presented: Basic and Advanced, being the first one opened by default.
In the basic tab, most common properties will be shown for the user to be fullfiled. They can have a default value and a description.
If the user wants a more accurate configuration of the instance, it can click the advanced tab in which other properties can be defined. They will have always a default value, and possibly a description.

**Comment by fjaviernieto** [comment]
The idea is to have a couple of tabs in the Experiments Tool, so one tab contains a minimum set of input parameters and another tab with a long list of input parameters. In the first case, other parameters will be configured with default values. It is intended to support non-experienced users.

**Comment by prudhomm** [comment]
Hence the notion of HPC ressources provider which can sell HPC ressources on the marketplace which can then be used by the user in the application. The HPC provider preconfigures his system to the best extent possible so that the interface for the user on these aspects are as simple as possible.

**Comment by prudhomm** [comment]
@emepetres I think having some kind of description of the issue and initial design discussion would help to understand where we are going. 
I would think that this issue do also in the StudentsTarget Milestone
