### ISSUE TITLE
One visualization desktop per user

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#34]
There is no need for an user to have more than one desktop active.

**Comment by victorsndvg** [comment]
Comment: probably this is already taken into accout. I think, at least, it is needed to be able to have one desktop per infrastructure

**Comment by emepetres** [comment]
@victorsndvg this is still valid?

**Comment by victorsndvg** [comment]
I think no. At leas I cannot figure out this use case. I think more than one desktop can be provided
