### ISSUE TITLE
One-Click behaviour

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#39]

**Comment by prudhomm** [comment]
@emepetres what do you mean by one-click behavior? you mean a simplified pipeline to launch the experiments?
 I would think that this should also go in the StudentsTarget Milestone.

**Comment by emepetres** [comment]
@prudhomm the purpose of the epic is to simplify the pipeline. It is not in the milestone because it was already too big, this will go in another one.
