### ISSUE TITLE
CKAN to deal with private data

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/MSOPortal#40]
@Trophime has found an interesting post about dealing with credentials to download private data from CKAN.

Here I paste the link to have it in mind.

https://stackoverflow.com/questions/38271351/download-resources-from-private-ckan-datasets

**Comment by emepetres** [comment]
We will be creating an MSO4SC storage for private data from CKAN

**Comment by victorsndvg** [comment]
HI @emepetres and @Trophime,

I'm taking a look to this. I did a fist approach using [ckanapi](https://github.com/ckan/ckanapi) to demonstrate that it's posible to deal with private datasets/data from CKan.

First of all, it's important the is possible to list **private CKan datasets** using the API (only metadata). In particular using the `package_search` action with the `include_private=True` option. Using `ckanapi` the call syntax is as follows:
```
$ ckanapi action package_search include_private=True -r http://CKAN_URL -a API_KEY
```
If logged-in, this list all datasets (including private datasets) with its metadata in JSON. To get the urls you can pipe the output to the following command:
```
$ python -c "import sys, json; results=json.load(sys.stdin)['results']; resources=[r['resources'][0] for r in results]; print([r['url'] for r in resources])"
```
*NOTE: this command only list 1 url per dataset*

If we know the name of the dataset (`<dataset-name>`) there are more ways to get its metadata:
```
$ ckanapi action package_show id=<dataset-name> -r http://CKAN_URL -a API_KEY 
```
or
```
$ ckanapi dump datasets <dataset-name> -r http://CKAN_URL -a API_KEY 
```
we can pipe the output to python to get the urls:
```
$ python -c "import sys, json; metadata=json.load(sys.stdin); resources=metadata['resources']; print([r['url'] for r in resources])"
```
Once we have the URLs pointing to private data we can get it with curl. Following 2 examples, one obtaining private data stored in CKAN itself, and other with data from GITLAB:
```
$ curl -H "Authorization: API_KEY" CKAN_PRIVATE_DATASET_URL -O FILENAME
```
and
```
$ curl -H 'PRIVATE-TOKEN: TOKEN' GITLAB_API_PRIVATE_RAW_FILE -O FILENAME
```

**Comment by emepetres** [comment]
from @victorsndvg :
- CKAN Ip
- Mount on the machine
- Integrate with CKAN

**Comment by emepetres** [comment]
See README to know how to use private datasets in the experiments tool
