### ISSUE TITLE
Slowness of the graphical interface

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#44]
- Orchestrator response seems to be slow sometimes
- Same with communications with Marketplace, maybe can be fixed in #29

**Comment by emepetres** [comment]
@Trophime pointed out that the marketplace is in debug mode by default. I'm making some changes to put it in production mode.

**Comment by prudhomm** [comment]
shouldn't this be reopen since marketplace is back in Debug mode ?
