### ISSUE TITLE
Bug in deploying in eye2brain in the marketplace

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#5]
Currently eye2brain cannot be deployed in the marketplace and have eye2brain deployed through the full pipeline

A hack is to hardwire/upload directly eye2brain at CESGA and the experiment tool, this is a temporary fix

/cc @gdolle @jbwahl

**Comment by emepetres** [comment]
@prudhomm could you explain a little bit the issue? Is the problem happening when creating the product?

**Comment by prudhomm** [comment]
The problem is the one mentioned by @gdolle during the hangout this morning

Le 17 janv. 2018 3:48 PM, "Javi Carnero" <notifications@github.com> a
écrit :
