### ISSUE TITLE
End-User stuck at Product Order 

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#61]
To reproduce:
 - order a product as a end-user
 - the product is in product orders

the developer has not received notifications of the purchase

<img width="1016" alt="screenshot 2018-05-24 12 10 39" src="https://user-images.githubusercontent.com/151693/40481062-7dd8bece-5f50-11e8-8000-4802c5c6f94b.png">

**Comment by emepetres** [comment]
This issue is still valid?

**Comment by Trophime** [comment]
No but it must be made clear in the docs how to accept an offer.
The only real issue here, for me, is how can the seller/owner be more efficiently be informed about a purchase demand.
But maybe @prudhomm has more comments on that

**Comment by prudhomm** [comment]
@emepetres this issue should be kept open, we had various end-users  stuck at this stage because the developer didn't get the notifications !
SEe #101 and #91 

@gdolle is on vacations and only he can access the marketplace, #91 needs to be setup so that other developers can accept new users. 
Also developers/app provides need to get notifications
