### ISSUE TITLE
display name of customer/seller/owner instead of hash

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#63]
Would it be possible to display name of customer/seller/owner instead of hash?

**Comment by emepetres** [comment]
Can you provide more information about this? Where is the hash being showed?

**Comment by prudhomm** [comment]
here is a screenshot of the product order:

<img width="982" alt="screenshot 2018-05-25 12 16 17" src="https://user-images.githubusercontent.com/151693/40539594-80d26d62-6015-11e8-97b5-cfd721b780dc.png">

**Comment by emepetres** [comment]
This a marketplace issue. I sent it to them to fix it (I know why it is happening, should be easy to fix).

**Comment by fdelavega** [comment]
Yes, completely agree. Probably this is going to happen in more places of the interface

**Comment by emepetres** [comment]
@prudhomm @Trophime can you confirm that the issue have been resolved?

**Comment by Trophime** [comment]
![marketplace_user_display](https://user-images.githubusercontent.com/1309311/41145580-dc95f48e-6b00-11e8-97ac-39382fb112b1.png)

The user name appears that's fine :+1: 
the trouble is that the name appears twice :-1:

**Comment by fdelavega** [comment]
Not really, the point is that the name is the First Name and the Last Name of the user, within its user profile. The IDM do not manage that fields, so it is filled with the user name

If you go to your user settings, and update your user profile with proper info, it will be displayed correcty

**Comment by fdelavega** [comment]
Here you can see the process:
<img width="875" alt="captura de pantalla 2018-06-08 a las 9 59 47" src="https://user-images.githubusercontent.com/2911173/41146233-ff06c4ec-6b02-11e8-9bc6-3f979464a5a1.png">

<img width="1233" alt="captura de pantalla 2018-06-08 a las 9 59 58" src="https://user-images.githubusercontent.com/2911173/41146245-07fc4edc-6b03-11e8-8483-f73293ef4b6a.png">

<img width="1261" alt="captura de pantalla 2018-06-08 a las 10 00 19" src="https://user-images.githubusercontent.com/2911173/41146257-12a0f0f4-6b03-11e8-9111-3a8c288620b9.png">

<img width="1237" alt="captura de pantalla 2018-06-08 a las 10 00 28" src="https://user-images.githubusercontent.com/2911173/41146271-1b68b0f0-6b03-11e8-91de-ec662c44b1c1.png">

**Comment by emepetres** [comment]
Thank you @fdelavega ! I'm closing the issue then.

**Comment by Trophime** [comment]
:+1:

**Comment by Trophime** [comment]
![marketplace_catalog](https://user-images.githubusercontent.com/1309311/41172525-6a58ff84-6b54-11e8-9377-36e0ee21a6ab.png)

I'm afraid that the bug has to be re-opened
