### ISSUE TITLE
user: cannot create an app instance

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#64]
When a user tries to "Create App instance" it fails with:

```Application doesnt belong to the user```

**Comment by prudhomm** [comment]
is this fixed? I still cannot use the portal

**Comment by emepetres** [comment]
working on it

**Comment by ernstn** [comment]
We get another issue at the same place, but only when end user tries to Create an Instanse. The owner can create it without any problem.

![issue](https://user-images.githubusercontent.com/36474718/40547681-d64c6208-6032-11e8-9013-6d6762d9493a.png)

**Comment by emepetres** [comment]
@ernstn could be this something related to an input you are entering wrongly? Are you using the exact same inputs as the owner?

If the error persists, please create a new issue indicating the blueprint you are using and how I could test it to find the bug, thanks.

**Comment by ernstn** [comment]
@emepetres don't have this error anymore. Probably it was fixed by your update. Thank you.
