### ISSUE TITLE
End-user cannot use application they don't own

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#66]
We have a critical issue in the portal, end-users who have bought applications but don't own them cannot use them. 
It means that currently, we cannot have end-users using MSO4SC
see the screenshot when I tried using the Feel++ toolboxes (which I don't own)
<img width="1023" alt="screenshot 2018-05-24 17 35 29" src="https://user-images.githubusercontent.com/151693/40509857-0fa7bcac-5f9b-11e8-9f99-9fc5263afd34.png">

**Comment by emepetres** [comment]
This is the same as #64

**Comment by prudhomm** [comment]
is it this change that fixed it ?
https://github.com/MSO4SC/MSOPortal/commit/282c0dd9e1b33085ab46b9ce6f0d82d216f66081

**Comment by prudhomm** [comment]
it would be nice to have a correspondance betwen the commits and the issues by using the #<issue ref>

**Comment by emepetres** [comment]
@prudhomm that's is usually done, but the commit you address is not related to this :)
