### ISSUE TITLE
marketplace errors

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#74]
These errors are obtained by connecting to the Marketplace

<img width="1079" alt="screenshot 2018-05-30 00 51 39" src="https://user-images.githubusercontent.com/151693/40689725-c892ed3e-63a3-11e8-9d41-dffa2f2969b6.png">

**Comment by victorsndvg** [comment]
@prudhomm , it's working for me now. Can you provide a more descriptive scenario of this issue?
