### ISSUE TITLE
Askbot integration

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#82]
Integration of Askbot with the portal.

The integration will not be done as an iframe, but as a new tab/window.

**Comment by Trophime** [comment]
I don't know if it has changed but when I first tried the askbot almost everything was written in Spanish...
The default language shall be English, I guess.

supporting multiple languages will be a must if feasible

**Comment by emepetres** [comment]
@victorsndvg can you provide some info about the english/spanish translation?

**Comment by victorsndvg** [comment]
I cannot understand. The service is in english. 

I don't see any spanish menu. What I see is a question written in spanish. We cannot control what users write

**Comment by Trophime** [comment]
sorry for this.. but last time I've tried it was in spanish
it's perfect now
