### ISSUE TITLE
Add documentation button 

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#86]
A documentation button should be available next to Visualusation, Experiments,... (or on the page) to provide documentation to the app instance, the end-user would expect this.
The documentation link is provided by the blueprint for example.

**Comment by emepetres** [comment]
The button will link to the book.

**Comment by prudhomm** [comment]
@emepetres we need a direct link to the app documentation I think. The end-user should have to know where to look for that. Do you agree ?
the documentation url could be in the blueprint for example
